### ISSUE TITLE
How to use DWTagList with auto layout

### ISSUE THREAD

**Issue by morteza2128** [domness/DWTagList#26]

**Comment by rahilbhansali** [comment]
Hi Domness - Thanks for an awesome github repo. I am having the same issue where the DW taglist is not taking up the correct height on first load in a tableviewcell with autolayout enabled. I have the automaticResize=Yes as a setting. 

It takes up the correct width upon scrolling out of the view and then returning to it. Any help would be appreciated.

**Comment by fuxlud** [comment]
Upvote!

**Comment by fabidona** [comment]
Upvote!

**Comment by domness** [comment]
Could you pull the latest from here and see if it works now?

**Comment by rahilbhansali** [comment]
Sure will pull and check! Thanks for updating! For now we used a temporary fix. Appreciate the library buddy thanks a lot!

**Comment by domness** [comment]
@rahilbhansali Any news?

**Comment by rahilbhansali** [comment]
Hi Domness,

Ended up doing it programatically since i was under time crunch then.
Haven't gotten around using autolayout for the DWTagList yet.

Regards,
Rahil Bhansali.
PH: +91-9820833010

**Comment by sunny45** [comment]
Superb..
