### ISSUE TITLE
Tags stack and display improperly in collection views after scrolling

### ISSUE THREAD

**Issue by AmazingVanish** [domness/DWTagList#29]
When used in a collection view, the tags sometimes don't display in their proper place. After scrolling down then back up, some tags get stacked and/or duplicated.

![screen shot 2015-08-28 at 11 49 10 am](https://cloud.githubusercontent.com/assets/192720/9552053/d0834850-4d7a-11e5-8b10-b1d280412bb5.png)

**Comment by AmazingVanish** [comment]
This also occurs when simply scrolling down through the collection view. It is more pronounced when scrolling back up.

**Comment by domness** [comment]
Could you pull the latest from here and see if it works now?

**Comment by AmazingVanish** [comment]
It appears to work now. Thanks!
